server:
  port: 8081

spring:
  application:
    name: trainer-workload-service
  datasource:
    url: jdbc:h2:mem:workloaddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    user: test
    password: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  token:
    access:
      secret-key: psofsdjfsdlkfkasdnfasdifjasdfjlasdkjflaksdjf
